### ISSUE TITLE
Laravel Nova 4.0 support

### ISSUE THREAD

**Issue by eboye** [mostafaznv/nova-video#2]
Hi,

I just saw that you've updated it to support Laravel 9 and hoped it supports Nova 4, but it doesn't. Could you make it support the new version of Nova?

Thanks

**Comment by mostafaznv** [comment]
Hi @eboye 

Please upgrade the package to `v3.0.0` and if there was any issue, please post it back

**Comment by eboye** [comment]
Will do, thanks

**Comment by eboye** [comment]
Working like a charm! Thanks!
