### ISSUE TITLE
dependsOn not working

### ISSUE THREAD

**Issue by handhikadj** [mostafaznv/nova-video#21]
I'm using laravel nova v4 and this package v4. noticed dependsOn not working.

**Current Behavior:**
there's no File (nova-video) upload field when I select "Upload a File" from the `Select`.

**Expected Behavior:**
there's File (nova-video) upload field when I select "Upload a File" from the `Select`.

https://github.com/mostafaznv/nova-video/assets/22522638/b1f87c4e-6434-413d-97f7-5f434e811c4e

**Comment by mostafaznv** [comment]
Hi @handhikadj,

You are using `v4` , and the `Dependent Fields` feature has been added to this package since [5.1.0](https://github.com/mostafaznv/nova-video/releases/tag/5.1.0).

If you'd like to use this feature, I recommend upgrading to the latest version or, at the very least, version 5.1.0.
