### ISSUE TITLE
How to play  

### ISSUE THREAD

**Issue by forgecodex** [mostafaznv/nova-video#23]
Like "https://file-examples.com/storage/fe7590659365eb907974df6/2017/04/file_example_MP4_480_1_5MG.mp4"

**Comment by mostafaznv** [comment]
Hi @BeiAduo 
Could you provide more details about the issue? What exactly is the problem?

**Comment by forgecodex** [comment]
Thanks for your reply, my question is; I know if the video is local to the server, it plays fine; but the video is an external link such as "https://file-examples.com/storage/fe7590659365eb907974df6/2017/04/file_example_MP4_480_1_5MG. mp4 "; What if it is played on the index page? 

By default, my domain name will be automatically added in front of the url;


Thanks

**Comment by mostafaznv** [comment]
NovaVideo was not designed to work without any type of `Storage`.
However, based on your explanation, it seems you want to use the NovaVideo field solely as a video player, rather than a video uploader. In this case, you may need a text field instead of a file field to insert/update the video.

I will try to implement this feature over the weekend. Stay tuned.

**Comment by forgecodex** [comment]
Thanks

**Comment by mostafaznv** [comment]
Hello,
Your requested feature has been implemented. To use this feature, please update the package to version [6.2.0](https://github.com/mostafaznv/nova-video/releases/tag/6.2.0)

Follow the instructions provided in the link below:
https://mostafaznv.gitbook.io/nova-video/advanced-usage/video-field-options/player-type

**Comment by forgecodex** [comment]
<img width="1220" alt="Screenshot 2024-03-15 at 2 46 19 PM" src="https://github.com/mostafaznv/nova-video/assets/79809955/8d1247ef-889f-418b-906e-ea78263cc9bb">

If you have time, can you add a set video width and height?

The current height takes up too much space;

Thank you very mach !

**Comment by mostafaznv** [comment]
Hi,

The height of the video is automatically set based on the loaded video's ratio. However, you can manually adjust it by adding custom CSS to your Nova panel. Have you tried that approach, or are you looking for a different solution?

**Comment by forgecodex** [comment]
Yes I have solved the problem with custom css, but it would be more flexible if you could set it by providing a height ;;
What I mean is that you just need to set the height of the index page.

Thank you

**Comment by mostafaznv** [comment]
Ok, I will take a look at it tomorrow.

I’m not sure about it, but I think adding an optional `max-height` to the index’s videos would be a good solution for that.

**Comment by forgecodex** [comment]
I think so ,
Thank you very much

**Comment by mostafaznv** [comment]
Your requested feature has been implemented.
Please update the package to version [6.3.0](https://github.com/mostafaznv/nova-video/releases/tag/6.3.0)

For more information, please refer to [this page](https://mostafaznv.gitbook.io/nova-video/advanced-usage/configuration/ui/player/direction-dir-1) or [this page](https://mostafaznv.gitbook.io/nova-video/advanced-usage/video-field-options/direction-dir-1).
